/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProposalRouteImport } from './routes/proposal'
import { Route as DeliverablesRouteImport } from './routes/deliverables'
import { Route as IndexRouteImport } from './routes/index'

const ProposalRoute = ProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverablesRoute = DeliverablesRouteImport.update({
  id: '/deliverables',
  path: '/deliverables',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deliverables': typeof DeliverablesRoute
  '/proposal': typeof ProposalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deliverables': typeof DeliverablesRoute
  '/proposal': typeof ProposalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deliverables': typeof DeliverablesRoute
  '/proposal': typeof ProposalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deliverables' | '/proposal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deliverables' | '/proposal'
  id: '__root__' | '/' | '/deliverables' | '/proposal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeliverablesRoute: typeof DeliverablesRoute
  ProposalRoute: typeof ProposalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proposal': {
      id: '/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof ProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliverables': {
      id: '/deliverables'
      path: '/deliverables'
      fullPath: '/deliverables'
      preLoaderRoute: typeof DeliverablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeliverablesRoute: DeliverablesRoute,
  ProposalRoute: ProposalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
